services:
  warp:
    image: warp
    platform: wasi/wasm
    build:
      context: ./warp
    runtime: io.containerd.wasmedge.v1
    ports:
      - 8080:8080
  warp-wasi:
    image: warp-wasi
    platform: wasi/wasm
    build:
      context: ./warp-wasi
    runtime: io.containerd.wasmedge.v1
    ports:
      - 9090:9090